const data = [
    velemer = {
        coords: [46.732679, 16.372416],
        name: "<h4><b class=heading>Velem&eacute;r - Chapel</b></h4>",
        desc: "<p>Medieval chapel with very valuable frescoes</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Velemér' target='_blank'>Check it Out!</a>",
    },
    oriszentpeter = {
        coords: [46.848369, 16.402039],
        name: "<h4><b class=heading>&#336;riszentp&eacute;ter - Church</b></h4>",
        desc: "<p>Medieval romanesque limestone church</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/%C5%90riszentp%C3%A9ter' target='_blank'>Check it Out!</a>",
    },
    jak = {
        coords: [47.139500, 16.581987],
        name: "<h4><b class=heading>J&#225;k - St. George's Church</b></h4>",
        desc: "<p>Large romanesque / early gothic church</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/J%C3%A1k' target='_blank'>Check it Out!</a>",
    },
    koszeg = {
        coords: [47.389612, 16.537560],
        name: "<h4><b class=heading>K&#337;szeg - Jurisics Castle</b></h4>",
        desc: "<p>Medieval and renaissance castle at the foothills of the Alps</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Jurisics_Castle' target='_blank'>Check it Out!</a>",
    },
    koszeg_church = {
        coords: [47.389342, 16.540466],
        name: "<h4><b class=heading>K&#337;szeg - St. James Church</b></h4>",
        desc: "<p>Cathedral with gothic medieval origins, and a baroque facade</p>",
        link: "<br> <a href='https://koszeg.hu/en/koszeg/varosnezes/latnivalok/st-james-church-3.html' target='_blank'>Check it Out!</a>",
    },
    csempeszkopacs = {
        coords: [47.152443, 16.799859],
        name: "<h4><b class=heading>Csempeszkop&#225;cs - Chapel</b></h4>",
        desc: "<p>Small hidden romanesque chapel with frescoes</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Csempeszkop%C3%A1cs' target='_blank'>Check it Out!</a>",
    },
    pityerszer = {
        coords: [46.865211, 16.340441],
        name: "<h4><b class=heading>Pityerszer - Skanzen (Historical Village)</b></h4>",
        desc: "<p>Model village of a 19th century rural Hungarian village</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Szalaf%C5%91' target='_blank'>Check it Out!</a>",
    },
    sopron = {
        coords: [47.685813, 16.590280],
        name: "<h4><b class=heading>Sopron - Historical District</b></h4>",
        desc: "<p>One of the most valuable historical districts in Hungary, with a medieval basilica, houses, and even synagogue!</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Sopron' target='_blank'>Check it Out!</a>",
    },
    pannonhalma = {
        coords: [47.552326, 17.761559],
        name: "<h4><b class=heading>Pannonhalma - Archabbey</b></h4>",
        desc: "<p>10th century base of a gothic church and Benedictine abbey, with historical library</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Pannonhalma_Archabbey' target='_blank'>Check it Out!</a>",
    },
    lebeny = {
        coords: [47.737350, 17.387466],
        name: "<h4><b class=heading>L&eacute;b&eacute;ny - St. James Church</b></h4>",
        desc: "<p>One of the best preserved romanesque churches of Hungary</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/L%C3%A9b%C3%A9ny#Romanesque_church' target='_blank'>Check it Out!</a>",
    },
    gyor = {
        coords: [47.689020, 17.630835],
        name: "<h4><b class=heading>Gy&#337;r - Bishop's Hill</b></h4>",
        desc: "<p>Fortified hill with basilica, medieval chapel, and palace</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Gy%C5%91r' target='_blank'>Check it Out!</a>",
    },
    sarvar = {
        coords: [47.251972, 16.937415],
        name: "<h4><b class=heading>S&#225;rv&#225;r - N&#225;dasdy Palace</b></h4>",
        desc: "<p>Originally renaissance fortification rebuilt in the 17th century to form a magnificent baroque palace</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/S%C3%A1rv%C3%A1r' target='_blank'>Check it Out!</a>",
    },
    somlo = {
        coords: [47.150052, 17.370149],
        name: "<h4><b class=heading>Soml&#243; Castle</b></h4>",
        desc: "<p>Medieval castle ruins on an extinct vulcano with magnificent views of the plains below</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Soml%C3%B3' target='_blank'>Check it Out!</a>",
    },
    csesznek = {
        coords: [47.350980, 17.880853],
        name: "<h4><b class=heading>Csesznek - Castle</b></h4>",
        desc: "<p>13th century castle in the midst of the Bakony mountains</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Castle_of_Csesznek' target='_blank'>Check it Out!</a>",
    },
    csobanc = {
        coords: [46.871778, 17.504617],
        name: "<h4><b class=heading>Csob&#225;nc - Ruins</b></h4>",
        desc: "<p>Medieval fortification ruins on an extinct vulcano, with some of the best views of the Balaton uplands</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Csob%C3%A1nc' target='_blank'>Check it Out!</a>",
    },
    devecser = {
        coords: [47.106001, 17.438023],
        name: "<h4><b class=heading>Devecser - Eszterh&#225;zy Palace</b></h4>",
        desc: "<p>Baroque palace of the Eszterh&#225;zy family</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Devecser' target='_blank'>Check it Out!</a>",
    },
    sumeg = {
        coords: [46.981947, 17.282941],
        name: "<h4><b class=heading>S&uuml;meg - Castle</b></h4>",
        desc: "<p>Mideval castle on a steep limestone peak</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Castle_of_S%C3%BCmeg' target='_blank'>Check it Out!</a>",
    },
    szigliget = {
        coords: [46.804096, 17.436733],
        name: "<h4><b class=heading>Szigliget - Castle</b></h4>",
        desc: "<p>Medieval castle on a steep peak, with wonderful views of lake Balaton below</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Szigliget' target='_blank'>Check it Out!</a>",
    },
    nagyvazsony = {
        coords: [46.984958, 17.695751],
        name: "<h4><b class=heading>Nagyv&#225;zsony - Kinizsi Castle</b></h4>",
        desc: "<p>Medieval limestone and basalt tower and castle</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Nagyv%C3%A1zsony' target='_blank'>Check it Out!</a>",
    },
    nagyvazsony_church = {
        coords: [46.988574, 17.703230],
        name: "<h4><b class=heading>Nagyv&#225;zsony - St. Stephen's Church</b></h4>",
        desc: "<p>Well preserved gothic church built by Pál Kinizsi</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Nagyv%C3%A1zsony' target='_blank'>Check it Out!</a>",
    },
    nagyvazsony_ruins = {
        coords: [46.985692, 17.689412],
        name: "<h4><b class=heading>Nagyv&#225;zsony - St. Michael's Abbey Ruins</b></h4>",
        desc: "<p>Ruins of a once large Pauline abbey destroyed duting the Ottoman wars</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Nagyv%C3%A1zsony' target='_blank'>Check it Out!</a>",
    },
    pecsely = {
        coords: [46.972241, 17.772304],
        name: "<h4><b class=heading>P&eacute;csely - Z&#225;dor Castle Ruins</b></h4>",
        desc: "<p>Medieval fortification ruins with imposing views of the Balaton uplands</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/P%C3%A9csely' target='_blank'>Check it Out!</a>",
    },
    tatika = {
        coords: [46.906189, 17.259957],
        name: "<h4><b class=heading>T&#225;tika Castle Ruins</b></h4>",
        desc: "<p>Hilltop ruins of a Medieval basalt castle</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/T%C3%A1tika-v%C3%A1r' target='_blank'>Check it Out!</a>",
    },
    varpalota = {
        coords: [47.201245, 18.139389],
        name: "<h4><b class=heading>V&#225;rpalota - Thury Palace</b></h4>",
        desc: "<p>Medieval and later renaissance fortification against the Ottomans, later palace</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/V%C3%A1rpalota' target='_blank'>Check it Out!</a>",
    },
    balaca = {
        coords: [47.044825, 17.887861],
        name: "<h4><b class=heading>Nemesv&#225;mos - Bal&#225;capuszta Roman villa</b></h4>",
        desc: "<p>Ruins of an ancient roman estate with mosaics, pottery, stables, walls, and paintings</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Bal%C3%A1capuszta' target='_blank'>Check it Out!</a>",
    },
    tac = {
        coords: [47.089959, 18.420757],
        name: "<h4><b class=heading>T&#225;c - Gorsium</b></h4>",
        desc: "<p>Ruins of the ansient Roman town Gorsium</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Gorsium' target='_blank'>Check it Out!</a>",
    },
    veszprem_church = {
        coords: [47.097108, 17.903294],
        name: "<h4><b class=heading>Veszpr&#233;m - St. Michael's Cathedral</b></h4>",
        desc: "<p>11th century romanesque cathedral, restored in the 19th century, with gothic underground chapel</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Veszpr%C3%A9m' target='_blank'>Check it Out!</a>",
    },
    veszprem_chapel = {
        coords: [47.096879, 17.903419],
        name: "<h4><b class=heading>Veszpr&#233;m - Blessed Gisela Chapel</b></h4>",
        desc: "<p>Medieval gothic chapel below the castle walls with valuable frescoes and carvings</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Veszpr%C3%A9m' target='_blank'>Check it Out!</a>",
    },
    margit = {
        coords: [47.099761, 17.900279],
        name: "<h4><b class=heading>Veszpr&#233;m - St. Catherine Abbey Ruins</b></h4>",
        desc: "<p>Ruins of a medieval abbey where St. Margaret of Hungary was raised before moving to Margaret Island (Budapest)</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Veszpr%C3%A9m' target='_blank'>Check it Out!</a>",
    },
    tihany = {
        coords: [46.913993, 17.889273],
        name: "<h4><b class=heading>Tihany - Benedictine Abbey</b></h4>",
        desc: "<p>Abbey with a medieval origin and basement chapel, and baroque chuch. 11th century king Andrew I bueried here. Beautiful views of lake Balaton</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Tihany_Abbey' target='_blank'>Check it Out!</a>",
    },
    keszthely_palace = {
        coords: [46.770841, 17.240893],
        name: "<h4><b class=heading>Keszthely - Festetics Palace</b></h4>",
        desc: "<p>Baroque palace of the Festetics family</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Festetics_Palace' target='_blank'>Check it Out!</a>",
    },
    keszthely_church = {
        coords: [46.764596, 17.243250],
        name: "<h4><b class=heading>Keszthely - Our Lady of Hungary Church</b></h4>",
        desc: "<p>Gothic church from the 14th century, with the largest medieval frescoes ever uncovered in Hungary</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Magyarok_Nagyasszonya-templom_(Keszthely)' target='_blank'>Check it Out!</a>",
    },
    felsoorrs = {
        coords: [47.013961, 17.951967],
        name: "<h4><b class=heading>Fels&#337;&#246;rs - Church of Mary Magdalene</b></h4>",
        desc: "<p>Romanesque church built in the 13th century from the area's iconic red sandstone</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Fels%C5%91%C3%B6rsi_pr%C3%A9posts%C3%A1gi_templom' target='_blank'>Check it Out!</a>",
    },
    egregy = {
        coords: [46.806957, 17.190701],
        name: "<h4><b class=heading>Egregy - St. Magdalene Chapel</b></h4>",
        desc: "<p>Tiny romanesque chapel with fresco fragments</p>",
        link: "<br> <a href='https://www.tripadvisor.ca/Attraction_Review-g274894-d8041840-Reviews-Mary_Magdalene_church_in_Egregy-Heviz_Zala_County_Western_Transdanubia.html' target='_blank'>Check it Out!</a>",
    },
    inota = {
        coords: [47.204628, 18.174222],
        name: "<h4><b class=heading>Inota - King St. Stephen Chapel</b></h4>",
        desc: "<p>19th century chapel with gothic medieval core and fresco fragments</p>",
        link: "<br> <a href='https://varlexikon.hu/inota' target='_blank'>Check it Out!</a>",
    },
    berhida = {
        coords: [47.112477, 18.134572],
        name: "<h4><b class=heading>Berhida - Church of the Saint Cross</b></h4>",
        desc: "<p>Gothic village church preserved in its entirety, even the tower (usually reconstructed)!</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Berhida' target='_blank'>Check it Out!</a>",
    },
    zirc = {
        coords: [47.263524, 17.873629],
        name: "<h4><b class=heading>Zirc - Cistercian Abbey</b></h4>",
        desc: "<p>Large baroque abbey with huge library in the middle of the Bakony mountains</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Zirc' target='_blank'>Check it Out!</a>",
    },
    szekesfehervar = {
        coords: [47.191395, 18.409833],
        name: "<h4><b class=heading>Sz&#233;kesfeh&#233;rv&#225;r - Historical District</b></h4>",
        desc: "<p>Ruins of the medieval coronation basilica of Hungary, gothic St. Anna chapel, turkish baths, and baroque buildings</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Sz%C3%A9kesfeh%C3%A9rv%C3%A1r' target='_blank'>Check it Out!</a>",
    },
    tata = {
        coords: [47.648896, 18.319380],
        name: "<h4><b class=heading>Tata - Castle</b></h4>",
        desc: "<p>Originally gothic and partially reconstructed castle on an island overlooking Lake Tata</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Tata,_Hungary' target='_blank'>Check it Out!</a>",
    },
    esztergom_castle = {
        coords: [47.798140890954194, 18.73660124427569],
        name: "<h4><b class=heading>Esztergom - Castle</b></h4>",
        desc: "<p>Fortifications of the earliest capital of Hungary: Esztergom. The king's chapel includes the earliest example of gothic architecture in Hungary (12th century)</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Tata,_Hungary' target='_blank'>Check it Out!</a>",
    },
    esztergom_basilika = {
        coords: [47.79905829166017, 18.736810605476567],
        name: "<h4><b class=heading>Esztergom - Basilika</b></h4>",
        desc: "<p>Most important and largest basilika in all of Hungary. Includes the one of a kind renaissance BakSoml&#243;cz chapel</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Esztergom_Basilica' target='_blank'>Check it Out!</a>",
    },
    vargesztes = {
        coords: [47.46801398850201, 18.39622975568398],
        name: "<h4><b class=heading>Gesztes Castle</b></h4>",
        desc: "<p>Hilltop ruins of a medieval castle in the V&#233;rtes hills</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/V%C3%A1rgesztes' target='_blank'>Check it Out!</a>",
    },
    visegrad = {
        coords: [47.793803920522926, 18.980204611330752],
        name: "<h4><b class=heading>Visegr&#225;d - Castle</b></h4>",
        desc: "<p>A very important castle in the history of Hungary, comprising of an ancient, lower, and upper castle overlooking the beautiful Danube bend. Below is the best preserved gothic palace in all of Hungary!</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Visegr%C3%A1d' target='_blank'>Check it Out!</a>",
    },
    zsambek = {
        coords: [47.549440013782196, 18.714855178693373],
        name: "<h4><b class=heading>Zs&#225;mb&#233;k - Church Ruins</b></h4>",
        desc: "<p>Ruins of a large romanesque and gothic church, destroyed by an earthquake in the 18th century</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Zs%C3%A1mb%C3%A9k' target='_blank'>Check it Out!</a>",
    },
    deg = {
        coords: [46.874801, 18.434184],
        name: "<h4><b class=heading>D&#233;g - Festetics Palace</b></h4>",
        desc: "<p>Festetics family palace, the only fully preserved classicist palace in Hungary.</p>",
        link: "<br> <a href='https://nof.hu/en/castles-palaces/palace-gardens/deg-festetics-mansion/' target='_blank'>Check it Out!</a>",
    },
    nograd = {
        coords: [47.906683, 19.045204],
        name: "<h4><b class=heading>N&#243;gr&#225;d Castle</b></h4>",
        desc: "<p>Medival castle in the northern hills of the country</p>",
        link: "<br> <a href='https://www.tripadvisor.ca/Attraction_Review-g11893585-d10046180-Reviews-Castle_of_Nograd-Nograd_Nograd_County_Northern_Hungary.html' target='_blank'>Check it Out!</a>",
    },
    holloko = {
        coords: [47.997616, 19.582157],
        name: "<h4><b class=heading>Holl&#243;k&#337; Castle and town</b></h4>",
        desc: "<p>Medival castle with tranditional scenic village in the northern mountains</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Holl%C3%B3k%C5%91' target='_blank'>Check it Out!</a>",
    },
    kisnana = {
        coords: [47.851076, 20.144483],
        name: "<h4><b class=heading>Kisn&#225;na Castle</b></h4>",
        desc: "<p>Castle and church ruins on the edge of the great plain</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Kisn%C3%A1na' target='_blank'>Check it Out!</a>",
    },
    sirok = {
        coords: [47.939423, 20.194398],
        name: "<h4><b class=heading>Sirok Castle</b></h4>",
        desc: "<p>Medival castle with scenic views on a sandstone hill</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Sirok' target='_blank'>Check it Out!</a>",
    },
    eger_var = {
        coords: [47.904023, 20.379368],
        name: "<h4><b class=heading>Eger Castle</b></h4>",
        desc: "<p>Historic castle in the middle of a historic city with museums and tours</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Eger_Castle' target='_blank'>Check it Out!</a>",
    },
    eger_minaret = {
        coords: [47.904704, 20.376565],
        name: "<h4><b class=heading>Eger Minaret</b></h4>",
        desc: "<p>Northernmost Ottoman historic site in the world. A testament to the scale of Ottoman occupation</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Eger_minaret' target='_blank'>Check it Out!</a>",
    },
    tarnaszentmaria = {
        coords: [47.878020, 20.202873],
        name: "<h4><b class=heading>Tarnaszentm&#225;ria Early Medival Church</b></h4>",
        desc: "<p>The oldest church in Hungary (10th century), with even some pagan hungarian elements</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Eger_mhttps://www.europeana.eu/en/item/2051943/data_euscreenXL_EUS_C5DA233DBDC34B3B8E207C2CE4544934inaret' target='_blank'>Check it Out!</a>",
    },
    belapatfalva = {
        coords: [48.049028, 20.364555],
        name: "<h4><b class=heading>B&#233;lap&#225;tfalva Cistercian Abbey</b></h4>",
        desc: "<p>Well preserved romanesque medieval abbey in the B&#252;kk mountains</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/B%C3%A9lap%C3%A1tfalva' target='_blank'>Check it Out!</a>",
    },
    diosgyor = {
        coords: [48.097889, 20.689810],
        name: "<h4><b class=heading>Di&#243;sgy&#337;r Palace</b></h4>",
        desc: "<p>Well renovated gothic palace near the city of Miskolc</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Di%C3%B3sgy%C5%91r' target='_blank'>Check it Out!</a>",
    },
    boldogko = {
        coords: [48.344416, 21.232608],
        name: "<h4><b class=heading>Boldogk&#337; Castle</b></h4>",
        desc: "<p>Well protected medival castle located on a volcanic opal dyke in the Zemplen mountains</p>",
        link: "<br> <a href='https://visithungary.com/articles/boldogko-castle-the-hidden-treasure-of-zemplen-mountains' target='_blank'>Check it Out!</a>",
    },
    fuzer = {
        coords: [48.542149, 21.460267],
        name: "<h4><b class=heading>F&#252;z&#233;r Castle</b></h4>",
        desc: "<p>Well renovated gothic castle in the scenic northern mountains</p>",
        link: "<br> <a href='https://visithungary.com/articles/fuzer-castle-the-middle-ages-reloaded' target='_blank'>Check it Out!</a>",
    },
    sarospatak_var = {
        coords: [48.316178, 21.568380],
        name: "<h4><b class=heading>S&#225;rospatak R&#225;k&#243;czy Palace</b></h4>",
        desc: "<p>Rare renaissance palace with renaissance and baroque buildings</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/S%C3%A1rospatak' target='_blank'>Check it Out!</a>",
    },
    sarospatak_templom = {
        coords: [48.318670, 21.568710],
        name: "<h4><b class=heading>S&#225;rospatak Basilica</b></h4>",
        desc: "<p>Medieval gothic basilica in eastern Hungary's most historic town</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/S%C3%A1rospatak' target='_blank'>Check it Out</a>",
    },
    sarospatak_templom = {
        coords: [48.318670, 21.568710],
        name: "<h4><b class=heading>S&#225;rospatak Basilica</b></h4>",
        desc: "<p>Medieval gothic basilica in eastern Hungary's most historic town</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/S%C3%A1rospatak' target='_blank'>Check it Out</a>",
    },
    gyula = {
        coords: [46.645790, 21.285762],
        name: "<h4><b class=heading>Gyula Castle</b></h4>",
        desc: "<p>Brick castle in the middle of the Hungarian plain</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Gyula,_Hungary' target='_blank'>Check it Out!</a>",
    },
    szeged_tower = {
        coords: [46.248635, 20.148703],
        name: "<h4><b class=heading>D&#246;m&#246;t&#246;r Tower</b></h4>",
        desc: "<p>Medieval bell brick tower (medieval sites are rare in the plains)</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/D%C3%B6m%C3%B6t%C3%B6r_Tower' target='_blank'>Check it Out!</a>",
    },
    ocsa = {
        coords: [47.289982, 19.226444],
        name: "<h4><b class=heading>&#211;csa Church</b></h4>",
        desc: "<p>Romanesque church just outside Budapest</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/%C3%93csa' target='_blank'>Check it Out!</a>",
    },
    rackeve = {
        coords: [47.160630, 18.943342],
        name: "<h4><b class=heading>R&#225;ckeve Orthodox Church</b></h4>",
        desc: "<p>Medieval Serbian orthodox church with frescoes</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Serbian_Kovin_Monastery' target='_blank'>Check it Out</a>",
    },
    szeged_church = {
        coords: [46.240598, 20.136317],
        name: "<h4><b class=heading>Szeged Franciscan Church</b></h4>",
        desc: "<p>Rare gothic church in the capital of the Hungarian plain</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Szegedi_ferences_templom_%C3%A9s_kolostor' target='_blank'>Check it Out!</a>",
    },
    kalocsa = {
        coords: [46.529173, 18.974049],
        name: "<h4><b class=heading>Kalocsa Baroque City</b></h4>",
        desc: "<p>Signature baroque town and bishop's seat</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Kalocsa' target='_blank'>Check it Out!</a>",
    },
    kisvarda = {
        coords: [48.226658, 22.078126],
        name: "<h4><b class=heading>Kisv&#225;rda Hybrid Church</b></h4>",
        desc: "<p>Medieval gothic church half rebuilt in the baroque style</p>",
        link: "<br> <a href='http://www.templomut.hu/uk/kisvarda/20' target='_blank'>Check it Out!</a>",
    },
    karcsa = {
        coords: [48.315453, 21.794616],
        name: "<h4><b class=heading>Karcsa Church</b></h4>",
        desc: "<p>Another hidden romanesque gem of eastern Hungary (built with brick)</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Karcsa' target='_blank'>Check it Out!</a>",
    },
    nyirbator = {
        coords: [47.837852, 22.135542],
        name: "<h4><b class=heading>Ny&#237;rb&#225;tor Church</b></h4>",
        desc: "<p>Rare late gothic church painted white since becoming a Calvinist church</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Ny%C3%ADrb%C3%A1tor' target='_blank'>Check it Out!</a>",
    },
    nyirbator = {
        coords: [47.837852, 22.135542],
        name: "<h4><b class=heading>Ny&#237;rb&#225;tor Church</b></h4>",
        desc: "<p>Rare late gothic church painted white since becoming a Calvinist church</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Ny%C3%ADrb%C3%A1tor' target='_blank'>Check it Out!</a>",
    },
    somogyvar = {
        coords: [46.594555, 17.639071],
        name: "<h4><b class=heading>Somogyv&#225;r Ruins</b></h4>",
        desc: "<p>Ruins of a historically crucial early medieval benedictine abbey. French monks from Saint-Gilles were originally invited to server here.</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Somogyv%C3%A1r_Abbey' target='_blank'>Check it Out!</a>",
    },
    puszta = {
        coords: [46.840060, 18.193055],
        name: "<h4><b class=heading>Puszta tower</b></h4>",
        desc: "<p>Tower of the church of a town abandoned during the Ottoman wars. The wooden and mud town has dissapeared but the strong brick church remains.</p>",
        link: "<br> <a href='https://foursquare.com/v/pusztatorony/61b4a9180ac45360827b2bd8' target='_blank'>Check it Out!</a>",
    },
    koroshegy = {
        coords: [46.832668, 17.899645],
        name: "<h4><b class=heading>K&#337;r&#246;shegy Church</b></h4>",
        desc: "<p>Medieval gothic church</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/K%C5%91r%C3%B6shegy' target='_blank'>Check it Out!</a>",
    },
    somogyvamos = {
        coords: [46.556299, 17.678360],
        name: "<h4><b class=heading>Somogyv&#225;mos Ruins</b></h4>",
        desc: "<p>Ruins of the church of another village abandoned during Ottoman occupation</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Somogyv%C3%A1mos' target='_blank'>Check it Out!</a>",
    },
    manfa = {
        coords: [46.158003, 18.227311],
        name: "<h4><b class=heading>M&#225;nfa Chapel</b></h4>",
        desc: "<p>Scenic medieval village chapel in the southern Mecsek mountains of Hungary</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/M%C3%A1nfa' target='_blank'>Check it Out!</a>",
    },
    cserkut = {
        coords: [46.075863, 18.134396],
        name: "<h4><b class=heading>Church of St. John the Baptist</b></h4>",
        desc: "<p>Another southern village medieval church in the Mecsek mountains with rare frescoes. Just outside of the cultural city of P&#233;cs</p>",
        link: "<br> <a href='https://commons.wikimedia.org/wiki/Category:Roman_Catholic_church_in_Cserk%C3%BAt' target='_blank'>Check it Out!</a>",
    },
    pecs_basilica = {
        coords: [46.078536, 18.223887],
        name: "<h4><b class=heading>P&#233;cs Cathedral</b></h4>",
        desc: "<p>Oldest basilica in Hungary still standing. Rebuilt in the original romanesque style in the 19th century. The crypt includes the graves of many significant people.</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/P%C3%A9cs_Cathedral' target='_blank'>Check it Out!</a>",
    },
    pecs_romans = {
        coords: [46.077774, 18.224885],
        name: "<h4><b class=heading>P&#233;cs Roman-Christian crypts</b></h4>",
        desc: "<p>Significant 3rd century ruins of the crypts of the ancient christians of Pannonia, way before the Hungarians arrived. UNESCO world heritage site!</p>",
        link: "<br> <a href='https://whc.unesco.org/en/list/853/#:~:text=In%20the%204th%20century%20A.D.,of%20P%C3%A9cs%2C%20in%20South%20Hungary.' target='_blank'>Check it Out!</a>",
    },
    pecs_mosque = {
        coords: [46.074254, 18.221313],
        name: "<h4><b class=heading>P&#233;cs Mosque and Minaret</b></h4>",
        desc: "<p>A significant Ottoman testament, the 16th century mosque is still used by muslims today</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Yakoval%C4%B1_Hasan_Pa%C5%9Fa_Mosque' target='_blank'>Check it Out!</a>",
    },
    pecs_mosquechurch = {
        coords: [46.077264, 18.227592],
        name: "<h4><b class=heading>P&#233;cs Mosque-Church</b></h4>",
        desc: "<p>16th century Ottoman mosque converted into a church. Most important piece of Ottoman architechture in all of Hungary.</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Mosque_of_Pasha_Qasim' target='_blank'>Check it Out!</a>",
    },
    pecsvarad = {
        coords: [46.159732, 18.412746],
        name: "<h4><b class=heading>P&#233;csv&#225;rad Castle Ruins</b></h4>",
        desc: "<p>Ruins of an early medieval abbey and castle. An important birthplace for many early-Hungarian documents.</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/P%C3%A9csv%C3%A1rad' target='_blank'>Check it Out!</a>",
    },
    siklos = {
        coords: [45.852431, 18.296344],
        name: "<h4><b class=heading>Sikl&#211;s Castle</b></h4>",
        desc: "<p>Gothic and later baroque palace with a well preserved chapel and gothic windows. One of the best preserved gothic palaces of Hungary.</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Castle_of_Sikl%C3%B3s' target='_blank'>Check it Out!</a>",
    },
];