const data = [
    velemer = {
        coords: [46.732679, 16.372416],
        name: "<h4><b class=heading>Velem&eacute;r - Chapel</b></h4>",
        desc: "<p>Medieval chapel with very valuable frescoes</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Velemér'>Check it Out!</a>",
    },
    oriszentpeter = {
        coords: [46.848369, 16.402039],
        name: "<h4><b class=heading>&#336;riszentp&eacute;ter - Church</b></h4>",
        desc: "<p>Medieval romanesque limestone church</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/%C5%90riszentp%C3%A9ter'>Check it Out!</a>",
    },
    jak = {
        coords: [47.139500, 16.581987],
        name: "<h4><b class=heading>J&#225;k - St. George's Church</b></h4>",
        desc: "<p>Large romanesque / early gothic church</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/J%C3%A1k'>Check it Out!</a>",
    },
    koszeg = {
        coords: [47.389612, 16.537560],
        name: "<h4><b class=heading>K&#337;szeg - Jurisics Castle</b></h4>",
        desc: "<p>Medieval and renaissance castle at the foothills of the Alps</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Jurisics_Castle'>Check it Out!</a>",
    },
    koszeg_church = {
        coords: [47.389342, 16.540466],
        name: "<h4><b class=heading>K&#337;szeg - St. James Church</b></h4>",
        desc: "<p>Cathedral with gothic medieval origins, and a baroque facade</p>",
        link: "<br> <a href='https://koszeg.hu/en/koszeg/varosnezes/latnivalok/st-james-church-3.html'>Check it Out!</a>",
    },
    csempeszkopacs = {
        coords: [47.152443, 16.799859],
        name: "<h4><b class=heading>Csempeszkop&#225;cs - Chapel</b></h4>",
        desc: "<p>Small hidden romanesque chapel with frescoes</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Csempeszkop%C3%A1cs'>Check it Out!</a>",
    },
    pityerszer = {
        coords: [46.865211, 16.340441],
        name: "<h4><b class=heading>Pityerszer - Skanzen (Historical Village)</b></h4>",
        desc: "<p>Model village of a 19th century rural Hungarian village</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Szalaf%C5%91'>Check it Out!</a>",
    },
    sopron = {
        coords: [47.685813, 16.590280],
        name: "<h4><b class=heading>Sopron - Historical District</b></h4>",
        desc: "<p>One of the most valuable historical districts in Hungary, with a medieval basilica, houses, and even synagogue!</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Sopron'>Check it Out!</a>",
    },
    pannonhalma = {
        coords: [47.552326, 17.761559],
        name: "<h4><b class=heading>Pannonhalma - Archabbey</b></h4>",
        desc: "<p>10th century base of a gothic church and Benedictine abbey, with historical library</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Pannonhalma_Archabbey'>Check it Out!</a>",
    },
    lebeny = {
        coords: [47.737350, 17.387466],
        name: "<h4><b class=heading>L&eacute;b&eacute;ny - St. James Church</b></h4>",
        desc: "<p>One of the best preserved romanesque churches of Hungary</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/L%C3%A9b%C3%A9ny#Romanesque_church'>Check it Out!</a>",
    },
    gyor = {
        coords: [47.689020, 17.630835],
        name: "<h4><b class=heading>Gy&#337;r - Bishop's Hill</b></h4>",
        desc: "<p>Fortified hill with basilica, medieval chapel, and palace</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Gy%C5%91r'>Check it Out!</a>",
    },
    sarvar = {
        coords: [47.251972, 16.937415],
        name: "<h4><b class=heading>S&#225;rv&#225;r - N&#225;dasdy Palace</b></h4>",
        desc: "<p>Originally renaissance fortification rebuilt in the 17th century to form a magnificent baroque palace</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/S%C3%A1rv%C3%A1r'>Check it Out!</a>",
    },
    somlo = {
        coords: [47.150052, 17.370149],
        name: "<h4><b class=heading>Soml&#243; Castle</b></h4>",
        desc: "<p>Medieval castle ruins on an extinct vulcano with magnificent views of the plains below</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Soml%C3%B3'>Check it Out!</a>",
    },
    csesznek = {
        coords: [47.350980, 17.880853],
        name: "<h4><b class=heading>Csesznek - Castle</b></h4>",
        desc: "<p>13th century castle in the midst of the Bakony mountains</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Castle_of_Csesznek'>Check it Out!</a>",
    },
    csobanc = {
        coords: [46.871778, 17.504617],
        name: "<h4><b class=heading>Csob&#225;nc - Ruins</b></h4>",
        desc: "<p>Medieval fortification ruins on an extinct vulcano, with some of the best views of the Balaton uplands</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Csob%C3%A1nc'>Check it Out!</a>",
    },
    devecser = {
        coords: [47.106001, 17.438023],
        name: "<h4><b class=heading>Devecser - Eszterh&#225;zy Palace</b></h4>",
        desc: "<p>Baroque palace of the Eszterh&#225;zy family</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Devecser'>Check it Out!</a>",
    },
    sumeg = {
        coords: [46.981947, 17.282941],
        name: "<h4><b class=heading>S&uuml;meg - Castle</b></h4>",
        desc: "<p>Mideval castle on a steep limestone peak</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Castle_of_S%C3%BCmeg'>Check it Out!</a>",
    },
    szigliget = {
        coords: [46.804096, 17.436733],
        name: "<h4><b class=heading>Szigliget - Castle</b></h4>",
        desc: "<p>Medieval castle on a steep peak, with wonderful views of lake Balaton below</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Szigliget'>Check it Out!</a>",
    },
    nagyvazsony = {
        coords: [46.984958, 17.695751],
        name: "<h4><b class=heading>Nagyv&#225;zsony - Kinizsi Castle</b></h4>",
        desc: "<p>Medieval limestone and basalt tower and castle</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Nagyv%C3%A1zsony'>Check it Out!</a>",
    },
    nagyvazsony_church = {
        coords: [46.988574, 17.703230],
        name: "<h4><b class=heading>Nagyv&#225;zsony - St. Stephen's Church</b></h4>",
        desc: "<p>Well preserved gothic church built by Pál Kinizsi</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Nagyv%C3%A1zsony'>Check it Out!</a>",
    },
    nagyvazsony_ruins = {
        coords: [46.985692, 17.689412],
        name: "<h4><b class=heading>Nagyv&#225;zsony - St. Michael's Abbey Ruins</b></h4>",
        desc: "<p>Ruins of a once large Pauline abbey destroyed duting the Ottoman wars</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Nagyv%C3%A1zsony'>Check it Out!</a>",
    },
    pecsely = {
        coords: [46.972241, 17.772304],
        name: "<h4><b class=heading>P&eacute;csely - Z&#225;dor Castle Ruins</b></h4>",
        desc: "<p>Medieval fortification ruins with imposing views of the Balaton uplands</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/P%C3%A9csely'>Check it Out!</a>",
    },
    tatika = {
        coords: [46.906189, 17.259957],
        name: "<h4><b class=heading>T&#225;tika Castle Ruins</b></h4>",
        desc: "<p>Hilltop ruins of a Medieval basalt castle</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/T%C3%A1tika-v%C3%A1r'>Check it Out!</a>",
    },
    varpalota = {
        coords: [47.201245, 18.139389],
        name: "<h4><b class=heading>V&#225;rpalota - Thury Palace</b></h4>",
        desc: "<p>Medieval and later renaissance fortification against the Ottomans, later palace</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/V%C3%A1rpalota'>Check it Out!</a>",
    },
    balaca = {
        coords: [47.044825, 17.887861],
        name: "<h4><b class=heading>Nemesv&#225;mos - Bal&#225;capuszta Roman villa</b></h4>",
        desc: "<p>Ruins of an ancient roman estate with mosaics, pottery, stables, walls, and paintings</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Bal%C3%A1capuszta'>Check it Out!</a>",
    },
    tac = {
        coords: [47.089959, 18.420757],
        name: "<h4><b class=heading>T&#225;c - Gorsium</b></h4>",
        desc: "<p>Ruins of the ansient Roman town Gorsium</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Gorsium'>Check it Out!</a>",
    },
    veszprem_church = {
        coords: [47.097108, 17.903294],
        name: "<h4><b class=heading>Veszpr&#233;m - St. Michael's Cathedral</b></h4>",
        desc: "<p>11th century romanesque cathedral, restored in the 19th century, with gothic underground chapel</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Veszpr%C3%A9m'>Check it Out!</a>",
    },
    veszprem_chapel = {
        coords: [47.096879, 17.903419],
        name: "<h4><b class=heading>Veszpr&#233;m - Blessed Gisela Chapel</b></h4>",
        desc: "<p>Medieval gothic chapel below the castle walls with valuable frescoes and carvings</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Veszpr%C3%A9m'>Check it Out!</a>",
    },
    margit = {
        coords: [47.099761, 17.900279],
        name: "<h4><b class=heading>Veszpr&#233;m - St. Catherine Abbey Ruins</b></h4>",
        desc: "<p>Ruins of a medieval abbey where St. Margaret of Hungary was raised before moving to Margaret Island (Budapest)</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Veszpr%C3%A9m'>Check it Out!</a>",
    },
    tihany = {
        coords: [46.913993, 17.889273],
        name: "<h4><b class=heading>Tihany - Benedictine Abbey</b></h4>",
        desc: "<p>Abbey with a medieval origin and basement chapel, and baroque chuch. 11th century king Andrew I bueried here. Beautiful views of lake Balaton</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Tihany_Abbey'>Check it Out!</a>",
    },
    keszthely_palace = {
        coords: [46.770841, 17.240893],
        name: "<h4><b class=heading>Keszthely - Festetics Palace</b></h4>",
        desc: "<p>Baroque palace of the Festetics family</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Festetics_Palace'>Check it Out!</a>",
    },
    keszthely_church = {
        coords: [46.764596, 17.243250],
        name: "<h4><b class=heading>Keszthely - Our Lady of Hungary Church</b></h4>",
        desc: "<p>Gothic church from the 14th century, with the largest medieval frescoes ever uncovered in Hungary</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Magyarok_Nagyasszonya-templom_(Keszthely)'>Check it Out!</a>",
    },
    felsoorrs = {
        coords: [47.013961, 17.951967],
        name: "<h4><b class=heading>Fels&#337;&#246;rs - Church of Mary Magdalene</b></h4>",
        desc: "<p>Romanesque church built in the 13th century from the area's iconic red sandstone</p>",
        link: "<br> <a href='https://hu.wikipedia.org/wiki/Fels%C5%91%C3%B6rsi_pr%C3%A9posts%C3%A1gi_templom'>Check it Out!</a>",
    },
    egregy = {
        coords: [46.806957, 17.190701],
        name: "<h4><b class=heading>Egregy - St. Magdalene Chapel</b></h4>",
        desc: "<p>Tiny romanesque chapel with fresco fragments</p>",
        link: "<br> <a href='https://www.tripadvisor.ca/Attraction_Review-g274894-d8041840-Reviews-Mary_Magdalene_church_in_Egregy-Heviz_Zala_County_Western_Transdanubia.html'>Check it Out!</a>",
    },
    inota = {
        coords: [47.204628, 18.174222],
        name: "<h4><b class=heading>Inota - King St. Stephen Chapel</b></h4>",
        desc: "<p>19th century chapel with gothic medieval core and fresco fragments</p>",
        link: "<br> <a href='https://varlexikon.hu/inota'>Check it Out!</a>",
    },
    berhida = {
        coords: [47.112477, 18.134572],
        name: "<h4><b class=heading>Berhida - Church of the Saint Cross</b></h4>",
        desc: "<p>Gothic village church preserved in its entirety, even the tower (usually reconstructed)!</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Berhida'>Check it Out!</a>",
    },
    zirc = {
        coords: [47.263524, 17.873629],
        name: "<h4><b class=heading>Zirc - Cistercian Abbey</b></h4>",
        desc: "<p>Large baroque abbey with huge library in the middle of the Bakony mountains</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Zirc'>Check it Out!</a>",
    },
    szekesfehervar = {
        coords: [47.191395, 18.409833],
        name: "<h4><b class=heading>Sz&#233;kesfeh&#233;rv&#225;r - Historical District</b></h4>",
        desc: "<p>Ruins of the medieval coronation basilica of Hungary, gothic St. Anna chapel, turkish baths, and baroque buildings</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Sz%C3%A9kesfeh%C3%A9rv%C3%A1r'>Check it Out!</a>",
    },
    tata = {
        coords: [47.648896, 18.319380],
        name: "<h4><b class=heading>Tata - Castle</b></h4>",
        desc: "<p>Originally gothic and partially reconstructed castle on an island overlooking Lake Tata</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Tata,_Hungary'>Check it Out!</a>",
    },
    esztergom_castle = {
        coords: [47.798140890954194, 18.73660124427569],
        name: "<h4><b class=heading>Esztergom - Castle</b></h4>",
        desc: "<p>Fortifications of the earliest capital of Hungary: Esztergom. The king's chapel includes the earliest example of gothic architecture in Hungary (12th century)</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Tata,_Hungary'>Check it Out!</a>",
    },
    esztergom_basilika = {
        coords: [47.79905829166017, 18.736810605476567],
        name: "<h4><b class=heading>Esztergom - Basilika</b></h4>",
        desc: "<p>Most important and largest basilika in all of Hungary. Includes the one of a kind renaissance BakSoml&#243;cz chapel</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Esztergom_Basilica'>Check it Out!</a>",
    },
    vargesztes = {
        coords: [47.46801398850201, 18.39622975568398],
        name: "<h4><b class=heading>Gesztes Castle</b></h4>",
        desc: "<p>Hilltop ruins of a medieval castle in the V&#233;rtes hills</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/V%C3%A1rgesztes'>Check it Out!</a>",
    },
    visegrad = {
        coords: [47.793803920522926, 18.980204611330752],
        name: "<h4><b class=heading>Visegr&#225;d - Castle</b></h4>",
        desc: "<p>A very important castle in the history of Hungary, comprising of an ancient, lower, and upper castle overlooking the beautiful Danube bend. Below is the best preserved gothic palace in all of Hungary!</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Visegr%C3%A1d'>Check it Out!</a>",
    },
    zsambek = {
        coords: [47.549440013782196, 18.714855178693373],
        name: "<h4><b class=heading>Zs&#225;mb&#233;k - Church Ruins</b></h4>",
        desc: "<p>Ruins of a large romanesque and gothic church, destroyed by an earthquake in the 18th century</p>",
        link: "<br> <a href='https://en.wikipedia.org/wiki/Zs%C3%A1mb%C3%A9k'>Check it Out!</a>",
    },
    deg = {
        coords: [46.874801, 18.434184],
        name: "<h4><b class=heading>D&#233;g - Festetics Palace</b></h4>",
        desc: "<p>Festetics family palace, the only fully preserved classicist palace in Hungary.</p>",
        link: "<br> <a href='https://nof.hu/en/castles-palaces/palace-gardens/deg-festetics-mansion/'>Check it Out!</a>",
    },
];